apiVersion: v1
kind: Service
metadata:
  labels:
    app: dns
  name: dns
spec:
  ports:
  - name: dns-udp
    port: 53
    protocol: UDP
    nodePort: 30001
  selector:
    app: dns
  type: NodePort
status:
  loadBalancer: {}
