apiVersion: v1
kind: Service
metadata:
  labels:
    app: mail
  name: mail
spec:
  externalTrafficPolicy: Local
  ports:
  - name: submissions
    port: 465
    protocol: TCP
    nodePort: 30002
  - name: smtp
    port: 25
    protocol: TCP
    nodePort: 30003
  - name: imap
    port: 993
    protocol: TCP
    nodePort: 30004
  selector:
    app: mail
  type: NodePort
status:
  loadBalancer: {}
